// <auto-generated />
using System;
using APR400BlazorLab1_MarcoTeranGutmanowitz.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APR400BlazorLab1_MarcoTeranGutmanowitz.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230918202213_changedFoundedDateToDateTime")]
    partial class changedFoundedDateToDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("APR400BlazorLab1_MarcoTeranGutmanowitz.Model.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("APR400BlazorLab1_MarcoTeranGutmanowitz.Model.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChampionshipsWon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StadiumName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("APR400BlazorLab1_MarcoTeranGutmanowitz.Model.TeamPlayerHistory", b =>
                {
                    b.Property<int>("TeamPlayerHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamPlayerHistoryId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPlayerHistory");
                });

            modelBuilder.Entity("APR400BlazorLab1_MarcoTeranGutmanowitz.Model.TeamPlayerHistory", b =>
                {
                    b.HasOne("APR400BlazorLab1_MarcoTeranGutmanowitz.Model.Player", "Player")
                        .WithMany("TeamPlayerHistories")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APR400BlazorLab1_MarcoTeranGutmanowitz.Model.Team", "Team")
                        .WithMany("TeamPlayerHistories")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("APR400BlazorLab1_MarcoTeranGutmanowitz.Model.Player", b =>
                {
                    b.Navigation("TeamPlayerHistories");
                });

            modelBuilder.Entity("APR400BlazorLab1_MarcoTeranGutmanowitz.Model.Team", b =>
                {
                    b.Navigation("TeamPlayerHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
